services:
  - type: web
    name: flavorfind-api
    runtime: docker
    region: frankfurt
    rootDir: backend
    dockerfilePath: ./Dockerfile

    envVars:
      - key: APP_NAME
        value: FlavorFind
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://flavorfind-22iw.onrender.com

      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: 134.209.20.131
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: flavorfind
      - key: DB_USERNAME
        value: flavorfind
      - key: DB_PASSWORD
        sync: false          # Set manually in Render dashboard

      - key: DB_SSLMODE
        value: prefer

      - key: CACHE_STORE
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database

      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error

      - key: BROADCAST_CONNECTION
        value: log
      - key: MAIL_MAILER
        value: log
